### ISSUE TITLE
TimeStamp Issues (postic/unix) 19 digits posix

### ISSUE THREAD

**Issue by lee-weedon** [Bugazelle/export-csv-to-influx#43]
Seems to be unable to import 19 digit posix dates

python3 csvtoinflux.py -i server1.csv -s server5:8086 --create --dbname NewTest --tagcolumns host --fieldcolumns CPU,GPU --metricname name --timecolumn time --timeformat posix
   _Deleting database NewTest
   Creating database NewTest
     Traceback (most recent call last):
       File "csvtoinflux.py", line 200, in <module>
        args.timezone, args.ssl)
       File "csvtoinflux.py", line 78, in loadCsv
           datetime_naive = datetime.datetime.fromtimestamp(int(row[timecolumn]))
OverflowError: timestamp out of range for platform time_t_

CSV looks like this :

name,time,CPU,GPU,host
temperature,1590335330162702714,53.5,53,server1
temperature,1590335335297033388,54,53,server1

**Comment by 7yl4r** [comment]
The relevant code is [here](https://github.com/Bugazelle/export-csv-to-influx/blob/20ed7533b0629b8fb9de2456273fec6c779ab118/src/ExportCsvToInflux/exporter_object.py#L429-L450). It would be great to have a test for this.

**Comment by Bugazelle** [comment]
Hello @lee-weedon 

Sorry for the delay
The latest lib 0.2.0 should fix your issue

Please upgrade to the latest version: `pip install ExportCsvToInflux  --upgrade`
